runtime: nodejs18

instance_class: F1

automatic_scaling:
  min_instances: 1

inbound_services:
  - warmup

env_variables:
  APP_ID: $APP_ID
  PUBLIC_KEY: $PUBLIC_KEY
  DISCORD_TOKEN: $DISCORD_TOKEN
  GUILD_ID: $GUILD_ID
