compatibility_date = "2023-09-17"
main = "src/index.ts"
name = "discord-rotom-bot"

kv_namespaces = [
  {binding = "NEWS_KV", id = "696d3e3efb594ffcb9edd17c44a82566"},
]

[triggers]
crons = ["*/5 * * * *"]
