compatibility_date = "2023-09-17"
main = "src/index.ts"
name = "discord-rotom-bot"

kv_namespaces = [
  {binding = "NEWS_KV", id = "696d3e3efb594ffcb9edd17c44a82566"},
]

# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true

[triggers]
crons = ["*/5 * * * *"]

[vars]
DISCORD_APPLICATION_ID = "1042274716624367636"
SENTRY_DSN = "https://4b26dd1cc3406cbcb327064a3e2a0f90@o4505734726549504.ingest.sentry.io/4505896349270016"
