name: 'Deployment'

on:
  push:
    branches:
      - main

env:
  CLOUD_RUN_SERVICE_NAME: discord-app

permissions:
  contents: 'read'
  id-token: 'write'

jobs:
  deploy-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: 'projects/272183910933/locations/global/workloadIdentityPools/github-actions-auth/providers/github-actions-auth'
          service_account: 'github-actions-deploy@discord-rotom-bot.iam.gserviceaccount.com'
      - uses: google-github-actions/setup-gcloud@v0
      - uses: actions/setup-node@v3
        with:
          node-version-file: 'package.json'
          cache: yarn
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - uses: golang-enthusiast/app-yaml-env-compiler@v1.0
        env:
          APP_ID: ${{ secrets.APP_ID }}
          PUBLIC_KEY: ${{ secrets.PUBLIC_KEY }}
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          GUILD_ID: ${{ secrets.GUILD_ID }}
      - name: Deploy app to Cloud Run
        run: gcloud app deploy --promote
      - name: Delete unused versions
        run: gcloud app versions list | grep 0.00 | awk '{print $2}' | xargs gcloud app versions delete
