name: 'Deployment'

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write
  packages: read

jobs:
  deploy-cf-workers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: 'package.json'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@lacolaco'
          always-auth: true
      - uses: pnpm/action-setup@v2
      - run: pnpm install --frozen-lockfile
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: pnpm run deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ vars.CLOUDFLARE_ACCOUNT_ID }}
  register-commands:
    needs: [deploy-cf-workers]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: 'package.json'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@lacolaco'
          always-auth: true
      - uses: pnpm/action-setup@v2
      - run: pnpm install --frozen-lockfile
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: pnpm run register-commands
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          DISCORD_APPLICATION_ID: ${{ vars.DISCORD_APPLICATION_ID }}
          DISCORD_GUILD_ID: ${{ vars.DISCORD_GUILD_ID }}
